In [1]:
import numpy as np

In [2]:
arr = np.arange(50)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
arr_atualizado = arr[arr % 2]

In [5]:
arr_atualizado

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1])

In [6]:
arr_atualizado = arr[arr > 5]

In [7]:
arr_atualizado

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
arr_atualizado = arr[arr <= 10]

In [9]:
arr_atualizado

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_atualizado = arr[(arr!= 1) | (arr!= 3)]

In [11]:
arr_atualizado

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
import numpy as np
# a) Crie um array aleatório de 15 itens entre 0 e 100;
arr = np.random.randint(100, size=15)
# b) Qual o maior número do array?
arr.max()
# c) Qual a sua posição?
list_arr = list(arr)
list_arr.index(arr.max())
# d) Verifique quais números do array são maior que 10;
arr[(arr > 10)]
# e) Salve em uma nova lista apenas os itens entre 10 e 30.
list_interval = arr[(arr >= 10) & (arr <= 30)]

In [13]:
list_arr = list(arr)

In [14]:
list_arr.index(arr.max())

2

In [15]:
arr.max()

97

In [16]:
arr[(arr > 10)]

array([96, 43, 97, 78, 62, 84, 96, 88, 35, 58, 40, 35, 19])

In [17]:
list_interval = arr[(arr >= 10) & (arr <= 30)]

In [18]:
list_interval

array([19])

In [19]:
matriz = np.vander(np.linspace(start=0, stop=100, retstep=20), )

/home/Faaeel06/.local/lib/python3.9/site-packages/numpy/lib/twodim_base.py:613: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = asarray(x)


In [20]:
matriz

array([[array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
                 8.16326531,  10.20408163,  12.24489796,  14.28571429,
                16.32653061,  18.36734694,  20.40816327,  22.44897959,
                24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
                32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
                40.81632653,  42.85714286,  44.89795918,  46.93877551,
                48.97959184,  51.02040816,  53.06122449,  55.10204082,
                57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
                65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
                73.46938776,  75.51020408,  77.55102041,  79.59183673,
                81.63265306,  83.67346939,  85.71428571,  87.75510204,
                89.79591837,  91.83673469,  93.87755102,  95.91836735,
                97.95918367, 100.        ])                           ,
        1],
       [2.0408163265306123, 1]], dtype=object)

In [39]:
matriz_1 = np.linspace(0, 100, 6)

In [40]:
matriz_1

array([  0.,  20.,  40.,  60.,  80., 100.])

In [35]:
matriz = np.random.randint(100, size=(5,2))

In [36]:
matriz

array([[ 1, 91],
       [58, 92],
       [12, 26],
       [49, 64],
       [80, 88]])