In [2]:
import numpy as np

In [3]:
np.random.rand(2, 3, 3)

array([[[0.98774145, 0.45015698, 0.795102  ],
        [0.3694459 , 0.88961633, 0.78088398],
        [0.21960297, 0.51305077, 0.19834434]],

       [[0.3557727 , 0.51248129, 0.8042032 ],
        [0.38481074, 0.84584774, 0.57507616],
        [0.61835569, 0.6652446 , 0.96250596]]])

In [4]:
np.random.randn(10, 10)

array([[ 0.22042876,  0.40626946,  0.78275623,  0.02607405, -1.21291356,
         0.8495106 ,  2.0006691 , -0.48091016, -0.17410409,  1.38023215],
       [-2.25136474, -0.40234435,  0.73903672, -1.22385432, -0.47008819,
         0.62381618, -0.28876374, -0.95145734,  0.91932736, -0.41099381],
       [-1.01458696,  0.78786909,  0.63042056, -0.33075681, -1.48659793,
         0.86080285,  0.07155116,  0.51591269, -0.39854802, -0.31497386],
       [-1.22207207, -1.36173333,  1.31926192,  0.80987429, -0.59931968,
         0.47039168,  0.28525252, -0.47530744, -1.64640832,  0.05322417],
       [ 1.66224724, -1.69887327, -0.34013829,  2.21710939, -0.26545815,
        -0.49018097, -2.40883445, -0.70950383,  0.51916168,  1.12109121],
       [ 0.57463269,  1.41629549,  0.12190948,  1.08310626, -1.60518057,
        -0.38741649, -0.36774139, -1.963312  , -0.07333304, -0.53111199],
       [ 0.26387416, -0.37165305, -1.08100974,  1.01196218,  0.88776621,
         1.53012351,  0.12637346, -0.47869042

In [5]:
np.random.randint(low=0, high=11, size=(4, 4))

array([[10,  6,  4, 10],
       [ 4,  2,  2,  2],
       [ 0,  9,  0, 10],
       [ 2,  1,  9,  4]])

In [6]:
a = np.array([1, 2, 3, 4, 5])

In [7]:
b = a.copy()
b

array([1, 2, 3, 4, 5])

In [8]:
b[-1] = 10
b

array([ 1,  2,  3,  4, 10])

In [9]:
a

array([1, 2, 3, 4, 5])

In [10]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matriz[0][1]

2

In [12]:
matriz[:, 1]

array([2, 5, 8])

In [13]:
matriz[:, [0, -1]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [14]:
np.diagonal(matriz)

array([1, 5, 9])

In [15]:
matriz.sum(axis=1)

array([ 6, 15, 24])

In [16]:
matriz_01 = np.random.randint(10, size=(3, 3, 3))
matriz_01

array([[[8, 3, 3],
        [0, 4, 7],
        [1, 9, 1]],

       [[0, 1, 7],
        [9, 0, 7],
        [6, 7, 2]],

       [[0, 8, 5],
        [6, 5, 5],
        [2, 2, 5]]])

In [22]:
matriz_01.sum(axis=2)

array([[14, 11, 11],
       [ 8, 16, 15],
       [13, 16,  9]])

In [28]:
matriz_02 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
matriz_02

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
matriz_03 = matriz_02.reshape(-1, 3)
matriz_03

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
matriz_03.reshape(-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
array_02 = np.array([1, 2, 3])
array_03 = np.array([4, 5, 6])

In [48]:
np.concatenate([array_02, array_03], axis=0)


array([1, 2, 3, 4, 5, 6])

In [49]:
np.vstack((array_02, array_03))

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.hstack((array_02, array_03))

array([1, 2, 3, 4, 5, 6])

In [52]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
np.eye(9, 7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [54]:
matriz01 = np.array([[-1, 3], [4, 2]])
matriz02 = np.array([[1, 2], [3, 4]])

In [57]:
np.matmul(matriz01, matriz02)

matriz01 @ matriz02

array([[ 8, 10],
       [10, 16]])

In [59]:
matriz03 = np.array([[1, 2], [3, 4], [5, 6]])
matriz03

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
matriz03.transpose(1, 0)

array([[1, 3, 5],
       [2, 4, 6]])

In [64]:
matriz04 = np.random.randint(10, size=(4, 3, 2))
matriz04

array([[[7, 7],
        [4, 6],
        [5, 3]],

       [[4, 3],
        [8, 5],
        [4, 8]],

       [[2, 6],
        [1, 0],
        [9, 7]],

       [[6, 4],
        [0, 8],
        [2, 7]]])

In [68]:
matriz04.transpose(1, 0, 2)

array([[[7, 7],
        [4, 3],
        [2, 6],
        [6, 4]],

       [[4, 6],
        [8, 5],
        [1, 0],
        [0, 8]],

       [[5, 3],
        [4, 8],
        [9, 7],
        [2, 7]]])

In [69]:
array_04 = np.array([1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2 ,2 ,2 , 2 ,2 , 2, 3, 3, 3, 3, 3, 3, 3 ,3 ,3, 4, 4, 4, 4 ,4 ,4 ,4 ,4 , 4, 5 , 5, 5, 5 , 5 ,5 , 5])

In [70]:
np.unique(array_04)

array([1, 2, 3, 4, 5])

In [ ]:
np.unique()