In [17]:
import numpy as np

In [18]:
lista = [1, 2, 3, 4, 5]
meu_array = np.array(lista)
meu_array

array([1, 2, 3, 4, 5])

In [19]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
meu_array_matriz = np.array(matriz)
meu_array_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.full(10, 20)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [25]:
np.empty(4)

array([ 2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
np.loadtxt('meu_array.txt', delimiter=',')

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [6., 7., 8., 9.]])

In [40]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
lista = [1, 2, 3, 4, 5, 6]
minha_lista = np.array(lista)
minha_lista


array([1, 2, 3, 4, 5, 6])

In [36]:
v_ou_f = [True, False, True, False, True, False]
v_ou_f_array = np.array(v_ou_f)
v_ou_f_array

array([ True, False,  True, False,  True, False])

In [37]:
minha_lista[v_ou_f_array]

array([1, 3, 5])

In [38]:
minha_lista[minha_lista % 2 == 0]

array([2, 4, 6])

In [39]:
minha_lista[minha_lista < 4]

array([1, 2, 3])

In [42]:
lista = np.zeros(10)


In [45]:
lista[6] = 20

In [46]:
lista

array([ 0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.,  0.])

In [52]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [47]:
def max_array(array):
    max_ = np.max(array)
    return np.ones(20) * max_

In [53]:
max_array(lista)

array([14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.,
       14., 14., 14., 14., 14., 14., 14.])

In [65]:
lista_01 = np.array([1, 2, 3, 4])

In [66]:
def vetor_func(vetor):
    vetor = np.array(vetor)
    vetor = vetor ** 2
    vetor = vetor + 3
    vetor = vetor[vetor != 4]
    vetor = vetor / 4

    return vetor


In [67]:
vetor_func(lista_01)

array([1.75, 3.  , 4.75])

In [74]:
def junta(array_01, array_02):

    return np.concatenate((array_01, array_02))

In [75]:
junta(lista, lista_01)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  1,  2,  3,
        4])

In [ ]:
def array_():