In [2]:
import numpy as np

## Questão 1 - Crie um numpy array com 10 elementos 0, exceto o elemento de índice 6, que deve ser 20

## Questão 2 - Crie uma função que receba um numpy array e retorne um array de 20 elementos contendo apenas o maior elemento do array recebido

## Questão 3 - Faça uma função que receba um array, eleve ele ao quadrado, some 3, pegue apenas o elementos que são diferentes de 4 e, por último, divida por 4. Depois, retorne esse array modificado

## Questão 4 - Faça uma função que receba dois array, junte os dois e retorne

## Questão 5 - Faça uma função que descreva meu array exibindo os seguintes dados com até 3 casas decimais: máx, min, média, desvio padrão (standard deviation). A exibição deve ser da seguinte forma:

```
******************************
Array: [0, 5, 6, 8, 9]

Max: 9
Min: 0
Media: 5.6
Desvio padrao: 3.137
******************************
```

In [3]:
meu_array = np.zeros(10)
meu_array[6] = 20
meu_array

array([ 0.,  0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.])

In [4]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [5]:
def max_array(array):
    max_ = np.max(array)
    return np.ones(20) * max_

In [6]:
max_array(lista)

array([14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.,
       14., 14., 14., 14., 14., 14., 14.])

In [7]:
def vetor_func(vetor):
    vetor = np.array(vetor)
    vetor = vetor ** 2
    vetor = vetor + 3
    vetor = vetor[vetor != 4]
    vetor = vetor / 4

    return vetor


In [8]:
vetor_func(lista)

array([ 1.75,  3.  ,  4.75,  7.  ,  9.75, 13.  , 16.75, 21.  , 25.75,
       31.  , 36.75, 43.  , 49.75])

In [20]:
lista_01 = np.array([1, 2, 3, 4])

In [10]:
def junta(array_01, array_02):

    return np.concatenate((array_01, array_02))

In [11]:
junta(lista, lista_01)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  1,  2,  3,
        4])

In [32]:
def array_(vetor):
    max = vetor.max()
    min = vetor.min()
    media = vetor.mean()
    desv_padr = vetor.std()

    print(f'{"*" * 30}\n'
          f'array: {vetor}\n\n'
          f'Máx: {max:.3f}\n'
          f'Min: {min:.3f}\n'
          f'Méd: {media:.3f}\n'
          f'Desvio Padrão: {desv_padr:.3f}'
          f'\n{"*" * 30}')   

In [30]:
array_1 = np.array([0, 5, 6, 8, 9])

In [33]:
array_(array_1)

******************************
array: [0 5 6 8 9]

Máx: 9.000
Min: 0.000
Méd: 5.600
Desvio Padrão: 3.137
******************************
